export const albumsTypes = {
  GET_ALBUMS_REQUEST: 'GET_ALBUMS_REQUEST',
  GET_ALBUMS_SUCCESS: 'GET_ALBUMS_SUCCESS',
  GET_ALBUMS_ERROR: 'GET_ALBUMS_ERROR',
  GET_ALBUM_DESCRIPTION_REQUEST: 'GET_ALBUM_DESCRIPTION_REQUEST',
  GET_ALBUM_DESCRIPTION_SUCCESS: 'GET_ALBUM_DESCRIPTION_SUCCESS',
  GET_ALBUM_DESCRIPTION_ERROR: 'GET_ALBUM_DESCRIPTION_ERROR',
  CLOSE_ALBUM_DESCRIPTION: 'CLOSE_ALBUM_DESCRIPTION',
  OPEN_ALBUM_DESCRIPTION: 'OPEN_ALBUM_DESCRIPTION',
};
